title: Hello, world! I'm Nathan Scott
description: > # this means to ignore newlines until "baseurl:"
  Nathan Scott a Self Taught Developer starting the 100 Days of Code Challenge, this website is used as a blog.
permalink: ':title/'
baseurl: "/Blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Nathan Scott # add your name
author-img: Image.png # add your photo
about-author: I am a self taught programmer with an interest in Software and Web Development, I created this blog on github pages to complete the coding challenge 100DaysOfCode, I will also use this site for future updates outside of 100DaysOfCode to keep a track of my progress. # add description
social-twitter: Xaensai # add your Twitter handle
social-facebook: XaenSai # add your Facebook handle
social-github: NathanScott85 # add your Github handle
social-linkedin: nathan-scott# add your Linkedin handle
social-email: nathansfeely@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
